version: "3"
services:
  app:
    image: openjdk:11-slim
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes: 
    #- "./fuyakake/build/libs/app.jar:/tmp/app.jar"
      - ../fuyakake:/srv:cached
        #entrypoint: "java -Djava.security.egd=file:/dev/./urandom -jar /tmp/app.jar"
  db:
    image: postgres:11.5
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "fuyakakeDb"
    ports:
      - "5432:5432"
    volumes:
      - "./docker/db/data:/var/lib/postgresql/data"
      - "./docker/db/initdb:/docker-entrypoint-initdb.d"
