CREATE ROLE fuyakakeuser WITH LOGIN PASSWORD 'fuyakakepass';
GRANT SELECT,UPDATE,INSERT,DELETE ON ALL TABLES IN SCHEMA public TO fuyakakeuser;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO fuyakakeuser;