INSERT INTO accounts(
    account_name,
    asset_ammount,
    category_type,
    user_id,
    create_date,
    create_user,
    update_date,
    update_user,
    version,
    delete_flag
)VALUES(
    '財布',
    10000,
    '1',
    'uhablog',
    current_timestamp,
    'uhablog',
    current_timestamp,
    'uhablog',
    1,
    'false'
);

INSERT INTO accounts(
    account_name,
    asset_ammount,
    category_type,
    user_id,
    create_date,
    create_user,
    update_date,
    update_user,
    version,
    delete_flag
)VALUES(
    'ケイスケの財布',
    10000,
    '1',
    'keisuke',
    current_timestamp,
    'keisuke',
    current_timestamp,
    'keisuke',
    1,
    'false'
);

INSERT INTO accounts(
    account_name,
    asset_ammount,
    category_type,
    user_id,
    create_date,
    create_user,
    update_date,
    update_user,
    version,
    delete_flag
)VALUES(
    '第二の財布',
    10000,
    '1',
    'keisuke',
    current_timestamp,
    'uhablog',
    current_timestamp,
    'uhablog',
    1,
    'false'
);

INSERT INTO accounts(
    account_name,
    asset_ammount,
    category_type,
    user_id,
    create_date,
    create_user,
    update_date,
    update_user,
    version,
    delete_flag
)VALUES(
    'uhablog第二の財布',
    10000,
    '1',
    'uhablog',
    current_timestamp,
    'uhablog',
    current_timestamp,
    'uhablog',
    1,
    'false'
);