INSERT INTO consumption(
    consumption_money,
    account_id,
    user_id,
    category_id,
    memo,
    date,
    create_date,
    create_user,
    update_date,
    update_user,
    version,
    delete_flag
)VALUES(
    3000,
    1,
    'uhablog',
    1,
    '電気代',
    now(),
    current_timestamp,
    'uhablog',
    current_timestamp,
    'uhablog',
    1,
    'false'
);