INSERT INTO middle_category_master(
    big_category_id,
    category_name,
    user_id,
    create_date,
    create_user,
    update_date,
    update_user,
    version,
    delete_flag
)VALUES(
    1,
    '給与',
    'guests',
    current_timestamp,
    'guests',
    current_timestamp,
    'guests',
    1,
    false
);

INSERT INTO middle_category_master(
    big_category_id,
    category_name,
    user_id,
    create_date,
    create_user,
    update_date,
    update_user,
    version,
    delete_flag
)VALUES(
    1,
    '副業収入',
    'guests',
    current_timestamp,
    'guests',
    current_timestamp,
    'guests',
    1,
    false
);

INSERT INTO middle_category_master(
    big_category_id,
    category_name,
    user_id,
    create_date,
    create_user,
    update_date,
    update_user,
    version,
    delete_flag
)VALUES(
    1,
    '不動産',
    'guests',
    current_timestamp,
    'guests',
    current_timestamp,
    'guests',
    1,
    false
);

INSERT INTO middle_category_master(
    big_category_id,
    category_name,
    user_id,
    create_date,
    create_user,
    update_date,
    update_user,
    version,
    delete_flag
)VALUES(
    1,
    '配当',
    'guests',
    current_timestamp,
    'guests',
    current_timestamp,
    'guests',
    1,
    false
);

INSERT INTO middle_category_master(
    big_category_id,
    category_name,
    user_id,
    create_date,
    create_user,
    update_date,
    update_user,
    version,
    delete_flag
)VALUES(
    1,
    'その他収入',
    'guests',
    current_timestamp,
    'guests',
    current_timestamp,
    'guests',
    1,
    false
);

-- 投資先
INSERT INTO middle_category_master(
    big_category_id,
    category_name,
    user_id,
    create_date,
    create_user,
    update_date,
    update_user,
    version,
    delete_flag
)VALUES(
    2,
    '株式',
    'guests',
    current_timestamp,
    'guests',
    current_timestamp,
    'guests',
    1,
    false
);

INSERT INTO middle_category_master(
    big_category_id,
    category_name,
    user_id,
    create_date,
    create_user,
    update_date,
    update_user,
    version,
    delete_flag
)VALUES(
    2,
    '投資信託',
    'guests',
    current_timestamp,
    'guests',
    current_timestamp,
    'guests',
    1,
    false
);

-- 自己投資
INSERT INTO middle_category_master(
    big_category_id,
    category_name,
    user_id,
    create_date,
    create_user,
    update_date,
    update_user,
    version,
    delete_flag
)VALUES(
    3,
    '書籍',
    'guests',
    current_timestamp,
    'guests',
    current_timestamp,
    'guests',
    1,
    false
);

INSERT INTO middle_category_master(
    big_category_id,
    category_name,
    user_id,
    create_date,
    create_user,
    update_date,
    update_user,
    version,
    delete_flag
)VALUES(
    3,
    'スクール代',
    'guests',
    current_timestamp,
    'guests',
    current_timestamp,
    'guests',
    1,
    false
);

-- 食費
INSERT INTO middle_category_master(
    big_category_id,
    category_name,
    user_id,
    create_date,
    create_user,
    update_date,
    update_user,
    version,
    delete_flag
)VALUES(
    4,
    '食費',
    'guests',
    current_timestamp,
    'guests',
    current_timestamp,
    'guests',
    1,
    false
);

INSERT INTO middle_category_master(
    big_category_id,
    category_name,
    user_id,
    create_date,
    create_user,
    update_date,
    update_user,
    version,
    delete_flag
)VALUES(
    4,
    '食料品',
    'guests',
    current_timestamp,
    'guests',
    current_timestamp,
    'guests',
    1,
    false
);

INSERT INTO middle_category_master(
    big_category_id,
    category_name,
    user_id,
    create_date,
    create_user,
    update_date,
    update_user,
    version,
    delete_flag
)VALUES(
    4,
    '外食',
    'guests',
    current_timestamp,
    'guests',
    current_timestamp,
    'guests',
    1,
    false
);

INSERT INTO middle_category_master(
    big_category_id,
    category_name,
    user_id,
    create_date,
    create_user,
    update_date,
    update_user,
    version,
    delete_flag
)VALUES(
    4,
    '朝ご飯',
    'guests',
    current_timestamp,
    'guests',
    current_timestamp,
    'guests',
    1,
    false
);

INSERT INTO middle_category_master(
    big_category_id,
    category_name,
    user_id,
    create_date,
    create_user,
    update_date,
    update_user,
    version,
    delete_flag
)VALUES(
    4,
    '昼ごはん',
    'guests',
    current_timestamp,
    'guests',
    current_timestamp,
    'guests',
    1,
    false
);

INSERT INTO middle_category_master(
    big_category_id,
    category_name,
    user_id,
    create_date,
    create_user,
    update_date,
    update_user,
    version,
    delete_flag
)VALUES(
    4,
    '夜ご飯',
    'guests',
    current_timestamp,
    'guests',
    current_timestamp,
    'guests',
    1,
    false
);

INSERT INTO middle_category_master(
    big_category_id,
    category_name,
    user_id,
    create_date,
    create_user,
    update_date,
    update_user,
    version,
    delete_flag
)VALUES(
    4,
    'カフェ',
    'guests',
    current_timestamp,
    'guests',
    current_timestamp,
    'guests',
    1,
    false
);

INSERT INTO middle_category_master(
    big_category_id,
    category_name,
    user_id,
    create_date,
    create_user,
    update_date,
    update_user,
    version,
    delete_flag
)VALUES(
    4,
    'その他食費',
    'guests',
    current_timestamp,
    'guests',
    current_timestamp,
    'guests',
    1,
    false
);

-- 日用品
INSERT INTO middle_category_master(
    big_category_id,
    category_name,
    user_id,
    create_date,
    create_user,
    update_date,
    update_user,
    version,
    delete_flag
)VALUES(
    5,
    '日用品',
    'guests',
    current_timestamp,
    'guests',
    current_timestamp,
    'guests',
    1,
    false
);

INSERT INTO middle_category_master(
    big_category_id,
    category_name,
    user_id,
    create_date,
    create_user,
    update_date,
    update_user,
    version,
    delete_flag
)VALUES(
    5,
    '子育て用品',
    'guests',
    current_timestamp,
    'guests',
    current_timestamp,
    'guests',
    1,
    false
);

INSERT INTO middle_category_master(
    big_category_id,
    category_name,
    user_id,
    create_date,
    create_user,
    update_date,
    update_user,
    version,
    delete_flag
)VALUES(
    5,
    'ドラッグストア',
    'guests',
    current_timestamp,
    'guests',
    current_timestamp,
    'guests',
    1,
    false
);

INSERT INTO middle_category_master(
    big_category_id,
    category_name,
    user_id,
    create_date,
    create_user,
    update_date,
    update_user,
    version,
    delete_flag
)VALUES(
    5,
    'お小遣い',
    'guests',
    current_timestamp,
    'guests',
    current_timestamp,
    'guests',
    1,
    false
);

INSERT INTO middle_category_master(
    big_category_id,
    category_name,
    user_id,
    create_date,
    create_user,
    update_date,
    update_user,
    version,
    delete_flag
)VALUES(
    5,
    'ペット用品',
    'guests',
    current_timestamp,
    'guests',
    current_timestamp,
    'guests',
    1,
    false
);

INSERT INTO middle_category_master(
    big_category_id,
    category_name,
    user_id,
    create_date,
    create_user,
    update_date,
    update_user,
    version,
    delete_flag
)VALUES(
    5,
    'タバコ',
    'guests',
    current_timestamp,
    'guests',
    current_timestamp,
    'guests',
    1,
    false
);

INSERT INTO middle_category_master(
    big_category_id,
    category_name,
    user_id,
    create_date,
    create_user,
    update_date,
    update_user,
    version,
    delete_flag
)VALUES(
    5,
    'その他日用品',
    'guests',
    current_timestamp,
    'guests',
    current_timestamp,
    'guests',
    1,
    false
);


-- 趣味・娯楽
INSERT INTO middle_category_master(
    big_category_id,
    category_name,
    user_id,
    create_date,
    create_user,
    update_date,
    update_user,
    version,
    delete_flag
)VALUES(
    6,
    'アウトドア',
    'guests',
    current_timestamp,
    'guests',
    current_timestamp,
    'guests',
    1,
    false
);

INSERT INTO middle_category_master(
    big_category_id,
    category_name,
    user_id,
    create_date,
    create_user,
    update_date,
    update_user,
    version,
    delete_flag
)VALUES(
    6,
    'ゴルフ',
    'guests',
    current_timestamp,
    'guests',
    current_timestamp,
    'guests',
    1,
    false
);

INSERT INTO middle_category_master(
    big_category_id,
    category_name,
    user_id,
    create_date,
    create_user,
    update_date,
    update_user,
    version,
    delete_flag
)VALUES(
    6,
    'スポーツ',
    'guests',
    current_timestamp,
    'guests',
    current_timestamp,
    'guests',
    1,
    false
);

INSERT INTO middle_category_master(
    big_category_id,
    category_name,
    user_id,
    create_date,
    create_user,
    update_date,
    update_user,
    version,
    delete_flag
)VALUES(
    6,
    '映画・音楽・ゲーム',
    'guests',
    current_timestamp,
    'guests',
    current_timestamp,
    'guests',
    1,
    false
);

INSERT INTO middle_category_master(
    big_category_id,
    category_name,
    user_id,
    create_date,
    create_user,
    update_date,
    update_user,
    version,
    delete_flag
)VALUES(
    6,
    '本',
    'guests',
    current_timestamp,
    'guests',
    current_timestamp,
    'guests',
    1,
    false
);

INSERT INTO middle_category_master(
    big_category_id,
    category_name,
    user_id,
    create_date,
    create_user,
    update_date,
    update_user,
    version,
    delete_flag
)VALUES(
    6,
    '旅行',
    'guests',
    current_timestamp,
    'guests',
    current_timestamp,
    'guests',
    1,
    false
);

INSERT INTO middle_category_master(
    big_category_id,
    category_name,
    user_id,
    create_date,
    create_user,
    update_date,
    update_user,
    version,
    delete_flag
)VALUES(
    6,
    '秘密の趣味',
    'guests',
    current_timestamp,
    'guests',
    current_timestamp,
    'guests',
    1,
    false
);

INSERT INTO middle_category_master(
    big_category_id,
    category_name,
    user_id,
    create_date,
    create_user,
    update_date,
    update_user,
    version,
    delete_flag
)VALUES(
    6,
    'その他趣味・娯楽',
    'guests',
    current_timestamp,
    'guests',
    current_timestamp,
    'guests',
    1,
    false
);

